name: CMake Build & Test
on:
  push:
    paths:
      - "**.cpp"
      - "**.c"
      - "**.hpp"
      - "**.h"
      - "**.inl"
      - "**/CMakeLists.txt"
  pull_request:
    paths:
      - "**.cpp"
      - "**.c"
      - "**.hpp"
      - "**.h"
      - "**.inl"
      - "**/CMakeLists.txt"
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Install Linux prerequisites
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake libgl1-mesa-dev ninja-build xorg-dev
      - uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'
      - name: Install Ninja for Windows
        if: runner.os == 'Windows'
        run: winget install --id Ninja-build.Ninja --accept-source-agreements --disable-interactivity
      - uses: actions/cache@v4
        with:
          path: build
          key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt','**/CMakePresets.json') }}
          restore-keys: |
            ${{ runner.os }}-cmake-
      - name: CMake configure
        run: |
          cmake -G "Ninja" -B build --preset Release -DBUILD_TESTS=ON
      - name: CMake build
        run: |
          cmake --build build --preset Release
      - uses: actions/upload-artifact@v4
        if: runner.os == 'Linux'
        with:
          name: test-artifacts
          path: build/tests
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: test-artifacts
          path: build/tests
      - name: CMake test
        run: |
          chmod +x build/tests/KukiTests
          ctest --test-dir build/tests --output-on-failure
